# Generated by Django 3.1.3 on 2020-12-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('locality', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('check_email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('username', models.CharField(max_length=200, primary_key='true', serialize=False)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=1000)),
                ('product_desc', models.CharField(max_length=1000)),
                ('product_price', models.CharField(max_length=200)),
                ('product_pic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('username', models.CharField(max_length=200, primary_key='true', serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('passw', models.CharField(max_length=200)),
                ('cpass', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cart_contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=1000)),
                ('product_desc', models.CharField(max_length=1000)),
                ('product_price', models.CharField(max_length=200)),
                ('product_pic', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
